{#*登录页 - 电共享服务用户服务协议 || 注册协议*#}

<div class="about_server">

    <p class="MsoNormal" align="center" style="text-align:center;">
        <b><span style="font-size:18px;">G</span></b><b><span>电共享服务用户服务协议<span></span></span></b>
    </p>

    <p>
        <strong><span>1.&nbsp;&nbsp;</span></strong><strong><span>提示内容</span></strong>
    </p>
    <p>
        <span>1.1&nbsp;</span><span>本《</span><span>G</span><span>电共享服务用户服务协议》（以下简称《协议》）是服务使用人（以下简称</span><span>“</span><span>用户</span><span>”</span><span>）与广西更电科技有限公司（以下简称</span><span>“</span><span>本公司</span><span>”</span><span>）之间关于用户下载、安装、使用</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件（包括但不限于</span><span>PC</span><span>版及移动电话、</span><span>PDA</span><span>版等各种无线手持终端版本的</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件），注册、使用、管理</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件账号，以及使用本公司提供的相关服务所订立的协议。</span>
    </p>
    <p>
        <span>1.2&nbsp;“G</span><span>电共享服务</span><span>”</span><span>软件由广西更电科技有限公司研发，并将按照本协议的规定及其不时发布的操作规则提供基于互联网以及移动网的相关服务，以下也称</span><span>“</span><span>本服务</span><span>”</span><span>或</span><span>“G</span><span>电共享服务服务</span><span>”</span><span>。为获得本服务，用户应认真阅读、充分理解本《协议》中各条款，特别涉及免除或者本公司责任的免责条款、限制用户权利的条款、约定争议解决方式、司法管辖、法律适用的条款。请您审慎阅读，一经点击</span><span>“</span><span>注册</span><span>”</span><span>按键，即表示同意接受本《协议》；如您不接受《本协议》的部分或全部内容，请您不要点击</span><span>“</span><span>注册</span><span>”</span><span>按键。（无民事行为能力人谢绝使用本服务，限制民事行为能力人应在法定监护人监护下阅读、理解及使用本服务等行为将视为对本《协议》的接受以及接受本《协议》各项条款的约束）。</span>
    </p>
    <p>
        <span>1.3&nbsp;</span><span>用户注册成功后，本公司将给予每个用户一个用户账号，该账号归本公司所有，用户完成申请注册手续后，获得账户的使用权。账号使用权仅属于初始申请注册人，禁止赠与、借用、租用、转让或售卖。用户承担账户与密码的保管责任，并就其账号及密码项下之一切活动负全部责任。</span>
    </p>
    <p>
        <span>1.4&nbsp;</span><span>审视阅读，您在申请注册过程中点击同意本协议之前，应当仔细阅读本协议。请您务必谨慎阅读，充分了解各条款内容，特别是免除或限制责任的条款、法律适用和争议解决条款。如您对本协议有任何疑问，请您向</span><span>“G</span><span>电共享服务</span><span>”</span><span>平台客服咨询。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>2.&nbsp;&nbsp;</span></strong><strong><span>知识版权说明</span></strong>
    </p>
    <p>
        <span>2.1&nbsp;</span><span>本</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件是由本公司开发。</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件的一切著作权、商标权、专利权、商业秘密等知识产权，以及相关的所有信息内容，包括但不限于：文字表述及其组合、图标、图示、色彩、界面设计、版面框架、有关数据、印刷材料、或电子文档等均受中华人民共和国著作权法、商标法、专利法、反不正当竞争法和相应的国际条约以及其他知识产权法律法规的保护，除涉及第三方授权的软件或技术外，本公司享受上述知识产权。</span>
    </p>
    <p>
        <span>2.2&nbsp;</span><span>未经本公司书面同意，用户不得为任何营利性或非营利性的目的自行实施、利用、转让或许可任何第三方实施、利用、转让上述知识产权，本公司保留追究上述未经许可使用责任的权利。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>3.&nbsp;&nbsp;</span></strong><strong><span>授权范围</span></strong>
    </p>
    <p>
        <span>3.1&nbsp;</span><span>用户可以为非商业目的在单一台终端设备上安装、使用、显示、运行</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件。用户不可以对本软件或者本软件运行过程中释放到任何计算机终端内存中的数据及本软件运行过程中客户端与服务端的交互数据进行复制、更改、修改、挂接运行或创作任何衍生作品，形式包括但不限于使用插件、外挂或非经授权的第三方工作</span><span>/</span><span>服务接入本软件和相关系统。</span>
    </p>
    <p>
        <span>3.2&nbsp;</span><span>未经本公司书面同意，用户不得将</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件安装在未经本公司明示许可的其他终端设备上，包括但不限于机顶盒、无线上网机、游戏机、电视机等。</span>
    </p>
    <p>
        <span>3.3&nbsp;</span><span>保留权利：未明示授权的其他一切权利仍归本公司所有，用户行使其他权利时须另外取得本公司的书面同意。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>4.&nbsp;&nbsp;</span></strong><strong><span>服务内容</span></strong>
    </p>
    <p>
        <span>4.1&nbsp;“G</span><span>电共享服务</span><span>”</span><span>服务的具体内容由本公司根据实际情况提供，主要包括用户的注册登陆、借还共享设备、评价及举报投诉、查询及分享使用服务等。</span>
    </p>
    <p>
        <span>4.2&nbsp;“G</span><span>电共享服务</span><span>”</span><span>提供的部分服务为收费服务，用户使用收费服务需要向本公司支付一定的费用。对于收费的服务，我们会尽量在用户使用前给予用户明确的提示，只有用户根据提示确认其愿意支付相关费用，用户才能使用该等收费服务。如用户拒绝支付相关费用，则本公司有权不向用户提供该等收费服务。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>5.&nbsp;&nbsp;</span></strong><strong><span>服务变更、中断及终止</span></strong>
    </p>
    <p>
        <span>5.1&nbsp;</span><span>用户同意本公司有权合理随时变更、中断或终止部分或全部的本服务（包括收费服务及免费服务）。如变更、终端或终止的服务属于免费服务，本公司无需通知用户，也无需对任何用户或任何第三方承担任何相应的法律责任；如变更、中断或终止的服务属于收费服务，本公司应当事先通知用户，并向受影响的用户提供等值的替代性收费服务，如已经向本公司支付了服务费的用户不愿意接受替代性的收费服务，本公司应当按照该用户实际使用相应收费服务的情况下扣除相应服务费之后将剩余的服务费退还给该用户。</span>
    </p>
    <p>
        <span>5.2&nbsp;</span><span>如发生以下任一情况，本公司有权随时中断或终止向用户提供本协议内的服务而无需对用户或任何第三方承担任何法律相关责任：</span>
    </p>
    <p>
        <span>（</span><span>1</span><span>）用户提供的个人资料的真实性、完整性、准确性、合法性、有效性存在问题；</span>
    </p>
    <p>
        <span>（</span><span>2</span><span>）用户违反本协议中规定的使用规则；</span>
    </p>
    <p>
        <span>（</span><span>3</span><span>）用户在使用收费服务时未按规定向本公司支付相应的服务费。</span>
    </p>
    <p>
        <span>5.3&nbsp;</span><span>用户注册的免费账号昵称和姓名如存在违反法律法规或国家政策要求，或侵犯任何第三方合法权益的情况，本公司有权禁止用户继续使用该账号、昵称。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>6.&nbsp;&nbsp;</span></strong><strong><span>使用规则</span></strong>
    </p>
    <p>
        <span>6.1&nbsp;</span><span>用户在申请使用</span><span>“G</span><span>电共享服务</span><span>”</span><span>服务时，必须向本公司提供准确、真实的个人相关资料。</span>
    </p>
    <p>
        <span>6.2&nbsp;</span><span>用户不应将其账号、密码转让或借予他人使用。如用户发现其账号遭他人非法使用，应立即通知本公司。因黑客行为或用户的保管疏忽导致账号、密码遭他人非法使用的，本公司不因此承担法律任何相关责任。如果您因为遗忘密码、账号被盗或其他原因无法登陆我公司账号，您可以按照我公司提供的联系方式进行申诉，但我公司并不对账户的找回做出任何的承诺和保证。</span>
    </p>
    <p>
        <span>6.3&nbsp;</span><span>用户同意本公司有权在提供本服务过程中以各种方式投放各种商业性广告或其他任何类型的商业信息，并且，用户同意接受本公司通过电子邮件或其他方式向用户发送商品促销或其他相关商业信息。</span>
    </p>
    <p>
        <span>6.4</span><span>用户同意本公司与政府单位或部门以及与本公司有合作“</span><span>G</span><span>电共享服务”的单位共享用户在“</span><span>G</span><span>电共享服务平台”的数据。</span>
    </p>
    <p>
        <span>6.5&nbsp;</span><span>用户在使用</span><span>“G</span><span>电共享服务</span><span>”</span><span>服务过程中，必须遵循以下原则：</span>
    </p>
    <p>
        <span>（</span><span>1</span><span>）遵守中国有关的法律和法规；</span>
    </p>
    <p>
        <span>（</span><span>2</span><span>）遵守所有与本服务有关的网络协议、规定和程序；</span>
    </p>
    <p>
        <span>（</span><span>3</span><span>）不得为任何非法目的而使用本服务；</span>
    </p>
    <p>
        <span>（</span><span>4</span><span>）不得以任何形式使用</span><span>“G</span><span>电共享服务</span><span>”</span><span>服务侵犯本公司的商业利益，包括但不限于发布非经本公司许可的商业或非商业广告；</span>
    </p>
    <p>
        <span>（</span><span>5</span><span>）不得利用</span><span>“G</span><span>电共享服务</span><span>”</span><span>服务系统进行任何可能对互联网或移动网正常运转造成不利影响的行为；</span>
    </p>
    <p>
        <span>（</span><span>6</span><span>）不得利用本产品提供的服务上传、展示或传播任何虚假的、骚扰性的、中伤他人的、辱骂性的、恐吓性的、庸俗淫秽的、或者其他任何非法信息资料；</span>
    </p>
    <p>
        <span>（</span><span>7</span><span>）不得侵犯其他任何第三方的专利权、著作权、商标权、名誉权或其他任何合法权益；</span>
    </p>
    <p>
        <span>（</span><span>8</span><span>）不得利用</span><span>“G</span><span>电共享服务</span><span>”</span><span>服务系统进行任何不利于本公司的行为；</span>
    </p>
    <p>
        <span>（</span><span>9</span><span>）禁止将</span><span>“G</span><span>电共享服务</span><span>”</span><span>设备恶意损坏，如有违反，本公司将保留追究法律责任的权利；禁止将</span><span>“G</span><span>电共享服务</span><span>”</span><span>设备占为己有，如需购买，请直接联系本公司客服。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>7.&nbsp;&nbsp;</span></strong><strong><span>服务使用及管理规定</span></strong>
    </p>
    <p>
        <span>7.1&nbsp;</span><span>用户应保证向本公司提供的所有注册资料是真实、完整、准确、合法、有效的。</span>
    </p>
    <p>
        <span>7.2&nbsp;</span><span>用户应为</span><span>16</span><span>周岁以上具有民事行为能力、精神状况健康正常的人士。如因没有民事行为能力、精神状况不健康的用户使用共享设备不当导致引起的一切责任与后果均由用户自行承担。</span>
    </p>
    <p>
        <span>7.3&nbsp;</span><span>本公司拥有</span><span>“G</span><span>电共享服务</span><span>”</span><span>共享设备的所有权、使用权以及许可用户使用共享设备的权利，并负责共享设备的日常投放、保养、维修。同时，</span><span>“G</span><span>电共享服务</span><span>”</span><span>服务系统的所有权及一切知识产权归本公司所有。</span>
    </p>
    <p>
        <span>7.4&nbsp;</span><span>移动电源为危险物品，在使用过程中小心轻放，勿碰撞，勿靠近火源、易燃物品，避免火灾。</span>
    </p>
    <p>
        <span>7.5&nbsp;</span><span>用户在使用过程中发现有设备损坏、电芯膨胀等现象，请不要使用并及时联系</span><span>“G</span><span>电共享服务</span><span>”</span><span>合作商家或本公司客服进行设备更换。</span>
    </p>
    <p>
        <span>7.6&nbsp;</span><span>用户应爱护本公司共享设备，并合理、正常、安全地使用。如在用户使用期间因用户使用或保管不当导致共享设备丢失、被窃、或损坏等，用户须赔偿本公司一切损失。</span>
    </p>
    <p>
        <span>7.7&nbsp;“G</span><span>电共享服务</span><span>”</span><span>移动电源与数据线搭配借还，用户在借还时候应及时检查移动电源与数据线是否能正常使用，如果不能正常使用，请及时向合作商家申请更换。</span>
    </p>
    <p>
        <span>7.8&nbsp;</span><span>用户不得利用本服务从事违法活动，不得恶意损坏、故意拆解共享设备及其相关配套设备，否则因此造成的损失及责任由用户承担。</span>
    </p>
    <p>
        <span>7.9&nbsp;</span><span>用户在显示有剩余设备的合作商家处借不到设备时，可对合作商家进行投诉。经本公司客服核实后，用户将获得平台奖励。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>8.&nbsp;&nbsp;</span></strong><strong><span>隐私保护</span></strong>
    </p>
    <p>
        <span>8.1&nbsp;</span><span>保护用户隐私是本公司的基本政策规范，本公司保证不随意对外公开或向第三方提供单个用户的注册资料及用户在使用本服务时存储在</span><span>“G</span><span>电共享服务</span><span>”</span><span>软件中的非公开内容。</span>
    </p>
    <p>
        <span>8.2&nbsp;</span><span>在不透露单个用户隐私资料的前提下，本公司有权对整个用户数据库进行分析并对用户数据库进行商业上的利用。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>9.&nbsp;&nbsp;</span></strong><strong><span>违约赔偿</span></strong>
    </p>
    <p>
        <span>9.1&nbsp;</span><span>如因本公司违反有关法律、法规或本协议的任何条款给用户造成损失，本公司同意承担由此造成的损害赔偿责任。</span>
    </p>
    <p>
        <span>9.2&nbsp;</span><span>用户同意保障和维护本公司及其他用户的利益，如因用户违反有关法律、法规或本协议中任何条款而给本公司或任何其他第三人称造成损失，用户同意承担由此造成的损害赔偿责任，包括但不限于赔偿本公司所有直接和间接损失。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>10.</span></strong><span style="font-size:9px;font-family:SimSun">&nbsp;</span><strong><span>争议及使用法律</span></strong>
    </p>
    <p>
        <span>10.1&nbsp;</span><span>本协议的订立、执行和解释及争议的解决均应适用中国法律并受中国法院管辖。</span>
    </p>
    <p>
        <span>10.2&nbsp;</span><span>如双方就本协议内容或其执行发生任何争议，双方应尽量友好协商解决；协商不成时，任何一方均可向本公司所在地的人民法院提起诉讼。</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <span>&nbsp;</span>
    </p>
    <p>
        <strong><span>11.</span></strong><span style="font-size:9px;font-family:SimSun">&nbsp;</span><strong><span>其他规定</span></strong>
    </p>
    <p>
        <span>11.1&nbsp;</span><span>如本协议中的任何条款无论因何种原因完全或部分无效或不具有执行力，本协议的其余条款仍应有效并且有约束力。</span>
    </p>
    <p>
        <span>11.2&nbsp;</span><span>本协议的标题仅为方便而设，在解释本协议时不应受该标题的限制。</span>
    </p>
    <p>
        <span>11.3&nbsp;</span><span>我公司对本协议具有法律规定范围内的解释权。</span>
    </p>
    <p>
        <span>11.4&nbsp;</span><span>联系我公司：若用户对本协议存在疑问，或者在使用本服务过程中需要向我公司反馈（含建议、投诉、举报等），请与我公司取得联系。</span>
    </p>
    <p>
        <span>联系电话：</span><span>{#settingfind('system', 'tel_num')#}</span>
    </p>
    <p>
        <span>客服</span><span>QQ</span><span>：</span><span>1925688583</span>
    </p>
    <p>
        <span>电子邮箱：</span><span>1925688583@qq.com</span>
    </p>
    <p>
        <span>官方网站：</span><span>www.gengdian.net</span>
    </p>
    <p>
        <br/>
    </p>

</div>
<style>
    .about_server {
        line-height: 20px;
        background: #ffffff;
        font-size: 16px;
        padding: 5px 16px
    }
</style>
<script>
    $JS = {
        refresh: false
    };
</script>